services:
  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: issue-tracker
    platform: linux/arm64
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/mariadb.conf.d/zz-my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: issue_tracker
      MYSQL_USER: issues
      MYSQL_PASSWORD: issues
    ports:
      - '33060:3306'

volumes:
  db_data:
