import type { Metadata } from 'next'

import '@/app/globals.css'
import '@/app/theme-config.css'
import '@radix-ui/themes/styles.css'

import NavBar from './NavBar'
import {
  AuthProvider,
  FontProvider,
  QueryClientProvider,
  StatusProvider,
  ThemeProvider,
  ToastProvider,
} from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning>
        <FontProvider>
          <QueryClientProvider>
            <AuthProvider>
              <ThemeProvider>
                <StatusProvider>
                  <ToastProvider>
                    <NavBar />
                    <main className='pt-16 px-5'>{children}</main>
                  </ToastProvider>
                </StatusProvider>
              </ThemeProvider>
            </AuthProvider>
          </QueryClientProvider>
        </FontProvider>
      </body>
    </html>
  )
}
