import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import { Theme } from '@radix-ui/themes'
import NavBar from './NavBar'
import { Inter } from 'next/font/google'

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={inter.variable}
      >
        <Theme accentColor="lime" grayColor="mauve">
          <NavBar />
          <main className="px-5">
            {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
