import type { Metadata } from 'next'
import '@/app/globals.css'
import '@radix-ui/themes/styles.css'
import '@/app/theme-config.css'
import { Theme } from '@radix-ui/themes'
import NavBar from './NavBar'
import { Inter } from 'next/font/google'
import AuthProvider from './auth/Provider'
import QueryClientProvider from '@/app/components/QueryClientProvider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={inter.variable}>
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor='lime' grayColor='mauve'>
              <NavBar />
              <main className='px-5'>{children}</main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
